# include $(APPDIR)/Make.defs

# CFLAGS += -I.
# CFLAGS += -I../
# CXXFLAGS += -I.
# CXXFLAGS += -I../

# # Source files - relative to this directory
# CSRCS = 
# CXXSRCS = ConsoleDisplay.cxx

# # # Include paths
# # CFLAGS += ${shell $(INCDIR) "$(CC)" $(TOPDIR)$(DELIM)include}
# # CXXFLAGS += ${shell $(INCDIR) "$(CXX)" $(TOPDIR)$(DELIM)include}
