set(ARCHCFLAGS          "-Wstrict-prototypes -Wno-attributes -Wno-unknown-pragmas -Wno-psabi")
set(ARCHCPUFLAGS        "-mlittle-endian  -mcpu=cortex-m0 -mthumb -mfloat-abi=soft -mthumb -Wa,-mthumb -Wa,-mimplicit-it=always")
set(ARCHCXXFLAGS        "-Wno-attributes -Wno-unknown-pragmas -Wno-psabi -std=gnu++20 -fno-exceptions -fcheck-new -fno-rtti")
set(ARCHPICFLAGS        "-fpic -msingle-pic-base -mpic-register=r10")
set(ARCHWARNINGS        "")
set(ARCHWARNINGSXX      "")
set(ARCHOPTIMIZATION    "-fomit-frame-pointer --param=min-pagesize=0 -fno-common -Wall -Wshadow -Wundef -ffunction-sections -fdata-sections -g")
set(CROSSDEV            "arm-none-eabi-")
set(CMAKE_C_COMPILER    "arm-none-eabi-gcc")
set(CMAKE_CXX_COMPILER  "arm-none-eabi-g++")
set(CMAKE_LINKER        "arm-none-eabi-ld")
set(CMAKE_OBJCOPY       "arm-none-eabi-objcopy")
set(CMAKE_OBJDUMP       "arm-none-eabi-objdump")
set(NXFLATLDFLAGS1      "-r -d -warn-common")
set(NXFLATLDFLAGS2      "-r -d -warn-common -T/workspace/nuttx/binfmt/libnxflat/gnu-nxflat-pcrel.ld -no-check-sections")
set(OBJEXT              ".o")
set(LIBEXT              ".a")
set(EXEEXT              "")
set(HOSTCC              "cc")
set(HOSTINCLUDES        "")
set(HOSTCFLAGS          "-O2 -Wall -Wstrict-prototypes -Wshadow -DHAVE_STRTOK_C=1")
set(HOSTLDFLAGS         "")
set(HOSTEXEEXT          "")
set(LDNAME              "raspberrypi-pico-flash.ld")
set(LDELFFLAGS          "-r -e main ")
set(LDMODULEFLAGS       "-r")
set(NUTTX_ARCH          "arm")
set(NUTTX_ARCH_CHIP     "rp2040")
set(NUTTX_BOARD         "raspberrypi-pico")
set(NUTTX_BUILD         "flat")
set(NUTTX_CXX           "cxx")
set(LLVM_ARCHTYPE       "thumbv6m")
set(LLVM_CPUTYPE        "cortex-m0")
set(LLVM_ABITYPE        "eabi")
set(EXTRA_LIBS       "/tools/gcc-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/13.2.1/thumb/v6-m/nofp/libgcc.a /tools/gcc-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/13.2.1/../../../../arm-none-eabi/lib/thumb/v6-m/nofp/libsupc++.a /tools/gcc-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/13.2.1/../../../../arm-none-eabi/lib/thumb/v6-m/nofp/libstdc++.a")
set(EXTRA_OBJS       "")
set(HEAD_OBJ         "")
set(LDENDGROUP       "")
set(LDFLAGS          "--print-memory-usage --entry=__start -nostdlib --gc-sections --cref -Map=/workspace/nuttx/nuttx.map")
set(LDSTARTGROUP     "")
set(LDLIBS     "-lsched -ldrivers -lboards -lc -lmm -larch -lm -lxx -lapps -lfs -lbinfmt -lnx -lopenamp -lboard -lboard ")
